[project]
name = "podgenai"
version = "0.19.0"
description = "OpenAI GPT based informational audiobook/podcast mp3 generator"
readme = "README.md"
authors = [
    { name = "Ouroboros Chrysopoeia", email = "impredicative@users.noreply.github.com" }
]
requires-python = ">=3.14"
license = "LGPL-3.0-only"
license-files = ["LICENSE"]
dependencies = [
    "click>=8.5.0",  # https://github.com/pallets/click/releases
    "openai>=3.5.0",  # https://github.com/openai/openai-python/releases
    "pathvalidate>=3.3.1",  # https://github.com/thombashi/pathvalidate/releases
    "python-dotenv>=1.2.3",  # https://github.com/theskumar/python-dotenv/releases
    "semantic-text-splitter>=0.32.0",  # https://github.com/benbrandt/text-splitter/releases https://github.com/benbrandt/text-splitter/tree/main/bindings/python
    "tiktoken>=0.14.0",  # https://github.com/openai/tiktoken/releases https://github.com/openai/tiktoken/blob/main/CHANGELOG.md
]
keywords = ["podcast", "mp3", "audiobook", "openai", "aicast"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Natural Language :: English",
    "Topic :: Multimedia :: Sound/Audio :: Speech",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14"
]

[project.scripts]
podgenai = "podgenai.__main__:main"

[project.urls]
Repository = "https://github.com/impredicative/podgenai"
Changelog = "https://github.com/impredicative/podgenai/releases"

[dependency-groups]
dev = [
    "poethepoet>=0.48.0",
    "ruff>=0.16.4",
    "ty>=0.0.73",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
source-exclude = ["/.env", "/archive", "/docs", "/scripts", "/work"]

[tool.ruff]
line-length = 320

[tool.ruff.lint]
ignore = ["DTZ005", "E731"]

[tool.poe.tasks]  # Run as "uv run poe <command>" or as "poe <command>".
check-lint = "ruff check"
check-format = "ruff format --check"
check-type = "ty check"
check = ["check-lint", "check-format", "check-type"]

fix-lint = "ruff check --fix"
fix-format = "ruff format"
fix = ["fix-lint", "fix-format"]

build = "uv build --clear --no-sources"
publish-dry = "uv publish --dry-run"
publish = "uv publish"
release = ["check", "build", "publish"]
release-dry = ["check", "build", "publish-dry"]
changes = { shell = "git log \"$(git describe --tags --abbrev=0)..HEAD\" --format='* %s'", help = "List commit messages since the latest git tag." }

uv-update = "uv self update"
uv-version = "uv self version"

upgrade-deps = "uv lock --upgrade"
outdated-deps = "uv tree --outdated"

describe = "python scripts/print_cached_episode_description.py"
serve = "python -m http.server 8000"  # For downloading generated mp3 from GitHub Codespace.
